### ISSUE TITLE
Can not start Session

### ISSUE THREAD

**Issue by mimmi20** [laminas/laminas-session#97] opened 2024-12-10 15:09 UTC
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.22.0

#### Summary

We are not able to start a Session after setting a Session ID. 

#### Current behavior

The Session does not start

#### How to reproduce

$sessionId = $routeMatch->getParam('sessionId');

$sessionManager->setId($sessionId);
$sessionManager->start();

#### Expected behavior

The Session starts.

#### Possible Cause

The Change in these [lines](https://github.com/laminas/laminas-session/compare/2.21.0...2.22.0#diff-8c351aa956ea03394b47a8a5d217e86224fea5fc21885112746c27ffae7fd81cL97-L98) may cause this.

**Comment by froschdesign** [comment] 2024-12-10 15:14
@mimmi20 
Is an exception thrown?

> The Change in these [lines](https://github.com/laminas/laminas-session/compare/2.21.0...2.22.0#diff-8c351aa956ea03394b47a8a5d217e86224fea5fc21885112746c27ffae7fd81cL97-L98) may cause this.

Is the link correct?

**Comment by mimmi20** [comment] 2024-12-10 15:33
> Is an exception thrown?

No.

> Is the link correct?

Yes.

![image](https://github.com/user-attachments/assets/06dbbccb-bfdf-4b17-90f8-88d3cbf55943)


We set a Session ID, but because of that the session will not be started.

**Comment by gsteel** [comment] 2024-12-10 15:55
This regression was introduced here:

https://github.com/laminas/laminas-session/pull/96/files#r1844718825

I shouldn't have let that go through because an 8.4 deprecation is no reason to break code running on 8.1+

If you have the time to send in a patch @mimmi20, I'll review and release quickly 👍

**Comment by gsteel** [comment] 2024-12-19 10:48
Closed via #98

**Closed as completed by gsteel** 2024-12-19 10:48 UTC
Labels: Bug
